import "./globals.css";
import { The_Girl_Next_Door } from 'next/font/google';

const theGirlNextDoor = The_Girl_Next_Door({
  weight: '400',
  subsets: ['cursive'],
  variable:'--font-girl-next-door',
});

export const metadata = {
  title: "UChristella - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
